name: .NET Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.102' # Use your .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests (If any)
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish


      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME  }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/trudoseadminportalapi:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERUSERNAME }}/trudoseadminportalapi:latest

      - name: Deploy to Google Cloud VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 35.208.113.104   # Replace with your Google Cloud instance IP
          username: trudoseinstance  # Replace with your instance username
          key: ${{ secrets.GCLOUD_SSH_PRIVATE_KEY }}
          script: |
            docker ps || true
